import Head from "next/head";
import styles from "@/styles/Allcase.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import ImageReveal from "@/component/ImageReveal/ImageReveal";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import { GoArrowUpRight, GoGlobe } from "react-icons/go";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { useEffect, useRef, useState } from "react";
import { BiSolidPhoneCall } from "react-icons/bi";
import Footer from "@/component/Footer/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import { RxEnvelopeClosed } from "react-icons/rx";
import { HiOutlineArrowRight } from "react-icons/hi";
import { FiChevronRight } from "react-icons/fi";

export default function AllCase() {
  useEffect(() => {
    AOS.init({ duration: 1000 }); // Customize duration if needed
  }, []);
  const portfolioData = [
    {
      title: "Operation Atlas",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-4.png",
    },
    {
      title: "Quantum Quest",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/1.jpg",
    },
    {
      title: "Blue Horizon Initiative",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-3.jpg",
    },
    {
      title: "Blue Horizon Initiative",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-4.jpg",
    },
  
    {
      title: "Operation Atlas",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-4.png",
    },
    {
      title: "Quantum Quest",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/1.jpg",
    },
    {
      title: "Blue Horizon Initiative",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-3.jpg",
    },
    {
      title: "Blue Horizon Initiative",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-4.jpg",
    },
    {
      title: "Blue Horizon Initiative",
      subtitle:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image: "/images/works-img-4.jpg",
    },
  ];
  return (
    <>
      <Head>
        <title>Dgtalists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/smart-logistic.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText
                    text={
                      "Case Studies "
                    }
                    highlightText={"Case"}
                  />
                </h1>
                <div className={styles.breadcrumb}>
                  <ol className={styles.breadcrumbWrap}>
                    <li className={styles.breadcrumbList}>
                      <a href="/">Home</a>
                    </li>
                    <li className={`${styles.breadcrumbList} ${styles.active}`}>
                      <FiChevronRight />
                      Case Studies
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>
      <section className={styles.portfolio}>
        <div className="container">
          <div className={styles.headerSection}>
            <span className={styles.subtitle}>our works</span>
            <h4 className={styles.title}>
              Excellence from <span className={styles.highlight}>concept</span>{" "}
              to completion
            </h4>         
          </div>

          {/* Swiper */}
         <div className="row">
            {portfolioData.map((portfolio, i) => (
              <div  className="col-lg-4" key={i}>
                <div className={styles.eachPortfolio}>
                  <div className={styles.portImgWrap}>
                    <ImageReveal
                      src={portfolio.image}
                      className={styles.portimg}
                    />
                    <div className={styles.industryBtn}>
                      <Link href={"#"}>
                        <GoArrowUpRight />
                      </Link>
                    </div>
                  </div>
                  <div className={styles.portfolioContent}>
                    <h4>
                      <Link href={"#"}>{portfolio.title}</Link>
                    </h4>
                    <p>{portfolio.subtitle}</p>
                  </div>
                  <div className={styles.techStack}>
                    <h6>Tech Stack</h6>
                    <ul>
                      <li>
                        <img src="/images/html-5.png" />
                      </li>
                      <li>
                        <img src="/images/css-3.png" />
                      </li>
                      <li>
                        <img src="/images/science.png" />
                      </li>
                      <li>
                        <img src="/images/programing.png" />
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            ))}
         </div>

          {/* Custom Navigation */}
        </div>
      </section>
      <section className={styles.workTogether}>
        <div className="container">
          <div className={styles.togetherBox}>
            <div className={styles.headerSection}>
              <span className={styles.subtitle}>Let's Collaborate</span>
              <h4 className={styles.title}>
                <AnimatedText
                  text={"Let’s Build Your Next-Gen Enterprise Solution"}
                  highlightText={"Next-Gen Enterprise"}
                />
              </h4>
              <p>
                Looking to enhance your enterprise operations with a scalable,
                secure, and high-performance software solution? Let’s talk!
              </p>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <BiSolidPhoneCall />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Contact Us</h5>
                    <Link href={"tel:+1 234 567 890"}>+1 234 567 890</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <GoGlobe />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Our Website</h5>
                    <Link href={"https://dgtalists.vercel.app/"}>
                      dgtalists.com
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <RxEnvelopeClosed />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>e-mail address</h5>
                    <Link href={"mailto:contact@dgtalists.com"}>
                      contact@dgtalists.com{" "}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
