import Head from "next/head";
import styles from "@/styles/About.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import ImageReveal from "@/component/ImageReveal/ImageReveal";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import { GoArrowUpRight, GoGlobe } from "react-icons/go";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import { BiSolidPhoneCall } from "react-icons/bi";
import Footer from "@/component/Footer/Footer";
import { FiChevronRight } from "react-icons/fi";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
import { RxEnvelopeClosed } from "react-icons/rx";


export default function Blog() {
  return (
    <>
      <Head>
        <title>Insights & Resources</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/blog.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText
                    text={"Insights & Resources"}
                    highlightText={"Insights"}
                  />
                </h1>

                {/* Breadcrumb */}
                <div className={styles.breadcrumb}>
                  <ol className={styles.breadcrumbWrap}>
                    <li className={styles.breadcrumbList}>
                      <a href="/">Home</a>
                    </li>
                    <li className={`${styles.breadcrumbList} ${styles.active}`}>
                      <FiChevronRight />
                      Insights & Resources
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>

      <section className={styles.latestBlogs}>
        <div className="container">
          <div className={styles.headerSection}>
            <span className={styles.subtitle}>latest blogs</span>
            <h4 className={styles.title}>
              <AnimatedText
                text={"Stay updated with our latest insights"}
                highlightText={"insights"}
              />
            </h4>
          </div>
          <div className="row">
            <div className="col-lg-4">
              <div className={styles.eachBlog}>
                <div className={styles.blogImg}>
                  {/* <img src="/images/post-1.jpg" alt="post"/> */}
                  <ImageReveal src={"/images/post-1.jpg"} alt={"post"} />
                </div>
                <div className={styles.postContent}>
                  <h5>
                    <Link href={"#"}>
                      The Future of Cybersecurity in the Digital Age
                    </Link>
                  </h5>
                  <Link className={styles.blogLink} href={"#"}>
                    read more <GoArrowUpRight />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachBlog}>
                <div className={styles.blogImg}>
                  <ImageReveal src={"/images/post-2.jpg"} alt={"post"} />
                </div>
                <div className={styles.postContent}>
                  <h5>
                    <Link href={"#"}>
                      The Importance of Data Privacy in Software Solutions
                    </Link>
                  </h5>
                  <Link className={styles.blogLink} href={"#"}>
                    read more <GoArrowUpRight />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachBlog}>
                <div className={styles.blogImg}>
                  <ImageReveal src={"/images/post-3.jpg"} alt={"post"} />
                </div>
                <div className={styles.postContent}>
                  <h5>
                    <Link href={"#"}>
                      How AI is Revolutionizing Software Development
                    </Link>
                  </h5>
                  <Link className={styles.blogLink} href={"#"}>
                    read more <GoArrowUpRight />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachBlog}>
                <div className={styles.blogImg}>
                  {/* <img src="/images/post-1.jpg" alt="post"/> */}
                  <ImageReveal src={"/images/post-1.jpg"} alt={"post"} />
                </div>
                <div className={styles.postContent}>
                  <h5>
                    <Link href={"#"}>
                      The Future of Cybersecurity in the Digital Age
                    </Link>
                  </h5>
                  <Link className={styles.blogLink} href={"#"}>
                    read more <GoArrowUpRight />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachBlog}>
                <div className={styles.blogImg}>
                  <ImageReveal src={"/images/post-2.jpg"} alt={"post"} />
                </div>
                <div className={styles.postContent}>
                  <h5>
                    <Link href={"#"}>
                      The Importance of Data Privacy in Software Solutions
                    </Link>
                  </h5>
                  <Link className={styles.blogLink} href={"#"}>
                    read more <GoArrowUpRight />
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className={styles.eachBlog}>
                <div className={styles.blogImg}>
                  <ImageReveal src={"/images/post-3.jpg"} alt={"post"} />
                </div>
                <div className={styles.postContent}>
                  <h5>
                    <Link href={"#"}>
                      How AI is Revolutionizing Software Development
                    </Link>
                  </h5>
                  <Link className={styles.blogLink} href={"#"}>
                    read more <GoArrowUpRight />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.workTogether}>
        <div className="container">
          <div className={styles.togetherBox}>
            <div className={styles.headerSection}>
              <span className={styles.subtitle}>Let's Collaborate</span>
              <h4 className={styles.title}>
                <AnimatedText
                  text={"Let’s Build Your Next-Gen Enterprise Solution"}
                  highlightText={"Next-Gen Enterprise"}
                />
              </h4>
              <p>
                Looking to enhance your enterprise operations with a scalable,
                secure, and high-performance software solution? Let’s talk!
              </p>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <BiSolidPhoneCall />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Contact Us</h5>
                    <Link href={"tel:+1 234 567 890"}>+1 234 567 890</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <GoGlobe />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Our Website</h5>
                    <Link href={"https://dgtalists.vercel.app/"}>
                      dgtalists.com
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <RxEnvelopeClosed />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>e-mail address</h5>
                    <Link href={"mailto:contact@dgtalists.com"}>
                      contact@dgtalists.com{" "}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
