import Head from "next/head";
import styles from "@/styles/Career.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import ImageReveal from "@/component/ImageReveal/ImageReveal";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import { GoArrowUpRight, GoGlobe } from "react-icons/go";
import ContinuousScrollingSlider from "@/component/Continious/ContinuousScrolig";
import { PiSuitcaseSimpleLight } from "react-icons/pi";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import Counter from "@/component/Counter/Counter";
import { useEffect, useRef, useState } from "react";
import { BiSolidPhoneCall } from "react-icons/bi";
import Footer from "@/component/Footer/Footer";
import { FiChevronRight } from "react-icons/fi";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
import { RxEnvelopeClosed } from "react-icons/rx";
import { LuSearchCode } from "react-icons/lu";

export default function Career() {
  return (
    <>
      <Head>
        <title>Career</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/team.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText text={"Career"} highlightText={"Career"} />
                </h1>

                {/* Breadcrumb */}
                <div className={styles.breadcrumb}>
                  <ol className={styles.breadcrumbWrap}>
                    <li className={styles.breadcrumbList}>
                      <a href="/">Home</a>
                    </li>
                    <li className={`${styles.breadcrumbList} ${styles.active}`}>
                      <FiChevronRight />
                      Career
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>

      <section className={styles.careerTop}>
        <div className="container">
          <div className="row">
            <div className="col-lg-6">
              <div className={styles.careerLeft}>
                <span className={styles.subtitle}>Grow With Us</span>
                <h4 className={styles.title}>
                  <AnimatedText text={"Why Join Us?"} highlightText={"Why"} />
                </h4>
                <p>
                  At Dgtalists, we don’t just offer jobs—we build careers. Our
                  culture is rooted in innovation, collaboration, and continuous
                  growth. Whether you’re a seasoned professional or just
                  starting out, we empower you with the tools, support, and
                  freedom to thrive.
                </p>

                <p>
                  We believe in recognizing talent, nurturing potential, and
                  creating a space where every voice matters. Join a team where
                  your ideas drive impact, and your success is our shared goal.
                </p>
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.careerRight}>
                <div className="row">
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/mission.png" alt="mission icon" />
                        </div>
                        <h5>Competitive Remuneration</h5>
                      </div>
                      <p>
                        We offer industry-aligned salary packages with regular
                        performance-based reviews.
                      </p>
                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/mission.png" alt="mission icon" />
                        </div>
                        <h5>Paid Time Off</h5>
                      </div>
                      <p>
                        Enjoy generous vacation, sick leave, and personal days
                        to recharge when you need it.
                      </p>
                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/mission.png" alt="mission icon" />
                        </div>
                        <h5>Learning & Development</h5>
                      </div>
                      <p>
                        Access to training, workshops, and courses to help you
                        grow your skills.
                      </p>
                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/mission.png" alt="mission icon" />
                        </div>
                        <h5>Flexible Work Hours</h5>
                      </div>
                      <p>
                        We believe in work-life balance with flexible schedules
                        and remote options.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.workTogether}>
        <div className="container">
          <div className={styles.togetherBox}>
            <div className={styles.headerSection}>
              <span className={styles.subtitle}>Let's Collaborate</span>
              <h4 className={styles.title}>
                <AnimatedText
                  text={"Let’s Build Your Next-Gen Enterprise Solution"}
                  highlightText={"Next-Gen Enterprise"}
                />
              </h4>
              <p>
                Looking to enhance your enterprise operations with a scalable,
                secure, and high-performance software solution? Let’s talk!
              </p>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <BiSolidPhoneCall />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Contact Us</h5>
                    <Link href={"tel:+91 89104 35874"}>+91 89104 35874</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <GoGlobe />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Our Website</h5>
                    <Link href={"https://dgtalists.com"}>dgtalists.com</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <RxEnvelopeClosed />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>e-mail address</h5>
                    <Link href={"mailto:contact@dgtalists.com"}>
                      contact@dgtalists.com{" "}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
