import Head from "next/head";
import styles from "@/styles/Career.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import ImageReveal from "@/component/ImageReveal/ImageReveal";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import { GoArrowUpRight, GoGlobe } from "react-icons/go";
import ContinuousScrollingSlider from "@/component/Continious/ContinuousScrolig";
import { PiSuitcaseSimpleLight } from "react-icons/pi";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import Counter from "@/component/Counter/Counter";
import { useEffect, useRef, useState } from "react";
import { BiSolidPhoneCall } from "react-icons/bi";
import Footer from "@/component/Footer/Footer";
import { FiChevronRight } from "react-icons/fi";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
import { RxEnvelopeClosed } from "react-icons/rx";
import { LuSearchCode } from "react-icons/lu";
import JobApplyModal from "@/component/JobApplyModal/JobApplyModal";
import { HiOutlineArrowRight, HiOutlineLocationMarker } from "react-icons/hi";
import { BsSuitcaseLg } from "react-icons/bs";
import { AiOutlineTags } from "react-icons/ai";

export default function Career() {
  const jobData = [
    {
      id: 1,
      title: "Frontend Developer",
      location: "Remote",
      jobType:"Full Time",
      experience: "2+ Years",
      description: "Build and maintain responsive web interfaces using React, HTML, and CSS. Work closely with designers and backend developers to deliver polished user experiences.",
    },
    {
      id: 2,
      title: "Backend Developer",
      location: "Bangalore, India",
      jobType:"Full Time",
      experience: "3+ Years",
      description: "Design and implement scalable RESTful APIs using Node.js, Express, and MongoDB. Optimize database queries and improve application performance.",
    },
    {
      id: 3,
      title: "UI/UX Designer",
      location: "Hybrid - Pune",
      jobType:"Full Time",
      experience: "1+ Years",
      description: "Create wireframes, prototypes, and UI mockups that align with user needs and business goals. Work closely with product teams to improve usability.",
    },
    {
      id: 4,
      title: "DevOps Engineer",
      location: "Chennai, India",
      jobType:"Full Time",
      experience: "3–5 Years",
      description: "Manage CI/CD pipelines, automate deployments, and ensure high availability of applications. Experience with AWS, Docker, and Kubernetes preferred.",
    },
    {
      id: 5,
      title: "Mobile App Developer",
      location: "Remote",
      jobType:"Full Time",
      experience: "2+ Years",
      description: "Develop and maintain cross-platform mobile apps using React Native. Integrate third-party APIs and ensure smooth user interactions across devices.",
    },
    {
      id: 6,
      title: "QA Engineer",
      location: "Delhi NCR",
      jobType:"Full Time",
      experience: "2–4 Years",
      description: "Write and execute test cases, identify bugs, and ensure product quality across web and mobile applications. Knowledge of automation tools is a plus.",
    },
    {
      id: 7,
      title: "Project Manager",
      location: "Hybrid - Mumbai",
      jobType:"Full Time",
      experience: "5+ Years",
      description: "Lead project planning, track progress, and coordinate between cross-functional teams. Ensure timely delivery and manage client communication effectively.",
    },
    {
      id: 8,
      title: "Full Stack Developer",
      location: "Remote",
      jobType:"Full Time",
      experience: "3+ Years",
      description: "Work on both frontend (React) and backend (Node.js) technologies. Build and maintain full-stack web applications, ensuring performance and scalability.",
    },
  ];
  
  const [selectedJob, setSelectedJob] = useState(null);

  const handleApplyClick = (job) => {
    setSelectedJob(job);
  };

  const closeModal = () => {
    setSelectedJob(null);
  };
  return (
    <>
      <Head>
        <title>Career</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/team.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText text={"Career"} highlightText={"Career"} />
                </h1>

                {/* Breadcrumb */}
                <div className={styles.breadcrumb}>
                  <ol className={styles.breadcrumbWrap}>
                    <li className={styles.breadcrumbList}>
                      <a href="/">Home</a>
                    </li>
                    <li className={`${styles.breadcrumbList} ${styles.active}`}>
                      <FiChevronRight />
                      Career
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>

      <section className={styles.careerTop}>
        <div className="container">
          <div className="row">
            <div className="col-lg-6">
              <div className={styles.careerLeft}>
                <span className={styles.subtitle}>Grow With Us</span>
                <h4 className={styles.title}>
                  <AnimatedText text={"Why Join Us?"} highlightText={"Why"} />
                </h4>
                <p>
                  At Dgtalists, we don’t just offer jobs—we build careers. Our
                  culture is rooted in innovation, collaboration, and continuous
                  growth. Whether you’re a seasoned professional or just
                  starting out, we empower you with the tools, support, and
                  freedom to thrive.
                </p>

                <p>
                  We believe in recognizing talent, nurturing potential, and
                  creating a space where every voice matters. Join a team where
                  your ideas drive impact, and your success is our shared goal.
                </p>
              </div>
            </div>
            <div className="col-lg-6">
              <div className={styles.careerRight}>
                <div className="row">
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/payroll.png" alt="mission icon" />
                        </div>
                        <h5>Competitive Remuneration</h5>
                      </div>
                      <p>
                        We offer industry-aligned salary packages with regular
                        performance-based reviews.
                      </p>
                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/deadline.png" alt="mission icon" />
                        </div>
                        <h5>Paid Time Off</h5>
                      </div>
                      <p>
                        Enjoy generous vacation, sick leave, and personal days
                        to recharge when you need it.
                      </p>
                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img src="/images/learn.png" alt="mission icon" />
                        </div>
                        <h5>Learning & Development</h5>
                      </div>
                      <p>
                        Access to training, workshops, and courses to help you
                        grow your skills.
                      </p>
                    </div>
                  </div>
                  <div className="col-lg-6">
                    <div className={styles.eachBox}>
                      <div className={styles.missionHeader}>
                        <div className={styles.missionIcon}>
                          <img
                            src="/images/working-hours.png"
                            alt="mission icon"
                          />
                        </div>
                        <h5>Flexible Work Hours</h5>
                      </div>
                      <p>
                        We believe in work-life balance with flexible schedules
                        and remote options.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.openPosition}>
        <div className="container">
          <div className={styles.careerHeader}>
            <span className={styles.subtitle}>Join Us</span>
            <h4 className={styles.title}>
              <AnimatedText
                text={"Current Openings"}
                highlightText={"Openings"}
              />
            </h4>
          </div>
          <div className="row">
            {jobData.map((job) => (
              <div className="col-lg-6" key={job.id}>
                <div className={styles.jobList}>
                  <h4>{job.title}</h4>
                  <ul>
                    <li><HiOutlineLocationMarker />{job.location}</li>
                    <li><BsSuitcaseLg />{job.experience}</li>
                    <li><AiOutlineTags />{job.jobType}</li>
                  </ul>
                  <p>{job.description}</p>
                  <button
                    className={styles.cmnBtn}
                    onClick={() => handleApplyClick(job)}
                  >
                    Apply
                    <HiOutlineArrowRight className={styles.arrowRight} />
                  </button>
                </div>
              </div>
            ))}
            {selectedJob && (
              <JobApplyModal job={selectedJob} onClose={closeModal} />
            )}
          </div>
        </div>
      </section>

      <section className={styles.workTogether}>
        <div className="container">
          <div className={styles.togetherBox}>
            <div className={styles.headerSection}>
              <span className={styles.subtitle}>Let's Collaborate</span>
              <h4 className={styles.title}>
                <AnimatedText
                  text={"Let’s Build Your Next-Gen Enterprise Solution"}
                  highlightText={"Next-Gen Enterprise"}
                />
              </h4>
              <p>
                Looking to enhance your enterprise operations with a scalable,
                secure, and high-performance software solution? Let’s talk!
              </p>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <BiSolidPhoneCall />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Contact Us</h5>
                    <Link href={"tel:+91 89104 35874"}>+91 89104 35874</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <GoGlobe />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Our Website</h5>
                    <Link href={"https://dgtalists.com"}>dgtalists.com</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <RxEnvelopeClosed />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>e-mail address</h5>
                    <Link href={"mailto:contact@dgtalists.com"}>
                      contact@dgtalists.com{" "}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
