import Head from "next/head";
import styles from "@/styles/Casestudy.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import ImageReveal from "@/component/ImageReveal/ImageReveal";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import { GoGlobe } from "react-icons/go";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination, Navigation } from "swiper/modules";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { useEffect, useRef, useState } from "react";
import { BiSolidPhoneCall } from "react-icons/bi";
import Footer from "@/component/Footer/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import { RxEnvelopeClosed } from "react-icons/rx";
import { FaRegCircleCheck } from "react-icons/fa6";
import { HiOutlineChevronDown, HiOutlineChevronUp } from "react-icons/hi";

export default function CaseStudy() {
  const [activeIndex, setActiveIndex] = useState(0);
  const swiperRef = useRef(null);
  const [showBackend, setShowBackend] = useState(true);
  const [showFrontend, setShowFrontend] = useState(false);
  useEffect(() => {
    AOS.init({ duration: 1000 }); // Customize duration if needed
  }, []);

  const images = [
    "/images/mobile-1.png",
    "/images/mab-2.png",
    "/images/mob-3.png",
    // Add more paths
  ];
  const webImg = [
    "/images/frontend.png",
    "/images/backend.png",
    "/images/mob-3.png",
    // Add more paths
  ];
  return (
    <>
      <Head>
        <title>Dgtalists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/news-app-2.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText
                    text={
                      "News App for Real-Time Updates & Community Engagement "
                    }
                    highlightText={"Real-Time"}
                  />
                </h1>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>
      <section className={styles.introSection}>
        <div className="container">
          <div className="row">
            <div className="col-lg-9">
              <div className={styles.introContent}>
                <img
                  className={styles.mainImg}
                  src="/images/news-app-1.jpg"
                  alt="intro"
                />
              </div>
            </div>
            <div className="col-lg-3">
              <div className={styles.projectDetails}>
                <div className={styles.eachDetails}>
                  <h4>Project Type</h4>
                  <p>Real-Time News & Community Platform</p>
                </div>
                <div className={styles.eachDetails}>
                  <h4>Category</h4>
                  <p>Social Networking</p>
                </div>
                
              </div>
              <div className={styles.projectDetails}>
                <div className={styles.eachDetails}>
                  <h4>Technology Stack</h4>
                  <ul>
                    <li>
                      <img src="/images/react.png" />
                    </li>
                    <li>
                      <img src="/images/php.png" />
                    </li>
                    <li>
                      <img src="/images/Laravel-3.png" />
                    </li>
                    <li>
                      <img src="/images/sql.png" />
                    </li>
                    <li>
                      <img src="/images/wordpress.png" />
                    </li>
                    <li>
                      <img src="/images/firebase.png" />
                    </li>
                    <li>
                      <img src="/images/facebook.png" />
                    </li>
                    <li>
                      <img src="/images/twitter.png" />
                    </li>
                    <li>
                      <img src="/images/instagram.png" />
                    </li>
                    <li>
                      <img src="/images/youtube.png" />
                    </li>
                  </ul>
                </div>
              </div>
             
            </div>
          </div>
          <div className={styles.introText} data-aos="fade-up">
            <h4 className={styles.title}>
              <AnimatedText
                text={"Project Overview"}
                highlightText={"Project"}
              />
            </h4>
            <p>
              In the era of digital media, having an interactive and engaging
              news platform is essential for delivering real-time updates and
              community-driven content. Our client, a leading digital media
              company, sought a modern hybrid news application to streamline
              content distribution, enhance audience engagement, and integrate
              social media channels.
            </p>
            <p>
              Dgtalists developed a feature-rich and scalable news hybrid app
              that empowers users to access, interact with, and share news
              seamlessly.
            </p>
          </div>
          <div className={styles.introText} data-aos="fade-up">
            <div className="row">
              <div className="col-lg-7">
                <h4 className={styles.title}>
                  <AnimatedText
                    text={"Challenges & Requirements"}
                    highlightText={"Challenges"}
                  />
                </h4>
                <ul>
                  <li>
                    The client required a robust digital news platform with:
                  </li>
                  <li>
                    <FaRegCircleCheck />
                    User-friendly navigation for browsing different news
                    categories.
                  </li>
                  <li>
                    <FaRegCircleCheck />
                    Seamless registration & login for readers and contributors.
                  </li>
                  <li>
                    <FaRegCircleCheck />
                    Advanced search & filtering options for easy content
                    discovery.
                  </li>
                  <li>
                    <FaRegCircleCheck />
                    Push notifications for instant updates on trending news.
                  </li>
                  <li>
                    <FaRegCircleCheck />
                    Social media integration for content sharing across
                    platforms.
                  </li>
                  <li>
                    <FaRegCircleCheck />
                    Multimedia support for articles, videos, and live news
                    updates.
                  </li>
                  <li>
                    <FaRegCircleCheck />A centralized content management system
                    for easy administration.
                  </li>
                </ul>
              </div>
              <div className="col-lg-5">
                <div className={styles.introImage}>
                  <ImageReveal
                  className={styles.keyImg}
                    src={"/images/challenge.jpg"}
                    alt="case-study-1"
                  />
                </div>
              </div>
            </div>
          </div>

          <div className={styles.introText} data-aos="fade-up">
            <h4 className={styles.title}>
              <AnimatedText text={"Our Solution"} highlightText={"Solution"} />
            </h4>
            <p>
              Dgtalists designed and developed a hybrid mobile and web news
              platform, ensuring a seamless and engaging experience for both
              users and content creators. The application was built to handle
              high traffic, multimedia content, and interactive features while
              maintaining performance and scalability.
            </p>
            <div className={styles.dropdownSection}>
              <h5
                onClick={() => setShowBackend(!showBackend)}
                className={styles.dropdownHeader}
              >
                1. Key Features Implemented
                {showBackend ? (
                  <HiOutlineChevronUp className={styles.arrowIcon} />
                ) : (
                  <HiOutlineChevronDown className={styles.arrowIcon} />
                )}
              </h5>
              {showBackend && (
                <ul className={styles.solutionList}>
                  <li>
                    <strong>User-Friendly Interface:</strong> Simple and
                    intuitive UI for easy news consumption.
                  </li>
                  <li>
                    <strong>Quick Registration & Secure Login :</strong> Email
                    and social media-based authentication.
                  </li>
                  <li>
                    <strong>Diverse News Categories:</strong>Organized content
                    based on different topics and regions.
                  </li>
                  <li>
                    <strong>Advanced Search & Filter Options:</strong> Enabling
                    users to find relevant articles effortlessly.
                  </li>
                  <li>
                    <strong>Push Notifications:</strong> Instant alerts for
                    breaking news and trending topics.
                  </li>
                  <li>
                    <strong>Social Media Integration:</strong> Allows users to
                    share news directly on Facebook, Twitter, and Instagram.
                  </li>
                  <li>
                    <strong> Interactive Content Features:</strong> Users can
                    like, comment, and engage with news articles.
                  </li>
                  <li>
                    <strong>Article & Video Upload Sections:</strong>Integrated
                    YouTube API for video news streaming.
                  </li>
                  <li>
                    <strong>Content Visibility & Engagement Metrics:</strong>{" "}
                    Admin panel to track reader interactions.
                  </li>
                  <li>
                    <strong>WordPress CMS Integration:</strong> For easy content
                    management and publishing.
                  </li>
                </ul>
              )}
            </div>

            <div className={styles.caseImage}>
            <div className="row">
                <div className="col-lg-4">
                  <ImageReveal
                    className={styles.caseStudyImage}
                    src={"/images/spincab.jpg"}
                    alt="case-study-2"
                  />
                </div>
                <div className="col-lg-4">
                  <ImageReveal
                    className={styles.caseStudyImage}
                    src={"/images/spincab.jpg"}
                    alt="case-study-2"
                  />
                </div>
                <div className="col-lg-4">
                  <ImageReveal
                    className={styles.caseStudyImage}
                    src={"/images/spincab.jpg"}
                    alt="case-study-2"
                  />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.introText} data-aos="fade-up">
            <h4 className={styles.title}>
              <AnimatedText
                text={"Business Impact"}
                highlightText={"Business"}
              />
            </h4>

            <ul className={styles.solutionList}>
              <li>
                <strong>Increased User Engagement:</strong> 40% rise in daily
                active users due to interactive content and real-time updates.
              </li>
              <li>
                <strong> Seamless Content Distribution:</strong>Enhanced reach
                through social media integration.
              </li>
              <li>
                <strong>Higher Retention Rates:</strong>Push notifications
                improved user retention by 35%.
              </li>
              <li>
                <strong>Improved Content Management:</strong> WordPress CMS
                simplified content updates for the admin team.
              </li>
            </ul>
          </div>
          <div className={styles.introText} data-aos="fade-up">
            <h4 className={styles.title}>
              <AnimatedText text={"Conclusion"} highlightText={"Conclusion"} />
            </h4>
            <p>
              Dgtalists successfully developed a highly functional News Channel
              Hybrid App, transforming the client’s digital media operations.
              The platform ensures seamless content consumption, real-time
              updates, and enhanced reader engagement, making it a game-changer
              in the digital news industry.
            </p>
          </div>
        </div>
      </section>
      <section className={styles.workTogether}>
        <div className="container">
          <div className={styles.togetherBox}>
            <div className={styles.headerSection}>
              <span className={styles.subtitle}>Let's Collaborate</span>
              <h4 className={styles.title}>
                <AnimatedText
                  text={"Let’s Build Your Next-Gen Enterprise Solution"}
                  highlightText={"Next-Gen Enterprise"}
                />
              </h4>
              <p>
                Looking to enhance your enterprise operations with a scalable,
                secure, and high-performance software solution? Let’s talk!
              </p>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <BiSolidPhoneCall />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Contact Us</h5>
                    <Link href={"tel:+91 89104 35874"}>+91 89104 35874</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <GoGlobe />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Our Website</h5>
                    <Link href={"https://dgtalists.com"}>dgtalists.com</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <RxEnvelopeClosed />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>e-mail address</h5>
                    <Link href={"mailto:contact@dgtalists.com"}>
                      contact@dgtalists.com{" "}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
