import Head from "next/head";
import styles from "@/styles/privacy.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import Footer from "@/component/Footer/Footer";
import { FiChevronRight } from "react-icons/fi";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
export default function Privacy() {
  return (
    <>
      <Head>
        <title>Privacy Policy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/privacy-bg.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText
                    text={"Privacy Policy"}
                    highlightText={"Privacy"}
                  />
                </h1>

                {/* Breadcrumb */}
                <div className={styles.breadcrumb}>
                  <ol className={styles.breadcrumbWrap}>
                    <li className={styles.breadcrumbList}>
                      <a href="/">Home</a>
                    </li>
                    <li className={`${styles.breadcrumbList} ${styles.active}`}>
                      <FiChevronRight />
                      Privacy Policy
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>

      <section className={styles.privacyWrapper}>
        <div className="container">
          <div className={styles.privacyWrapTop}>
            <h2>Privacy Policy</h2>
            <span>Effective Date: April 17, 2025</span>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>1.Information We Collect</h4>
            <p>We may collect the following types of information:</p>
            <ul>
              <li>
                <strong>Personal Information:</strong> Name, email address,
                phone number, company name, job title, etc.
              </li>
              <li>
                <strong>Technical Information:</strong> IP address, browser
                type, device information, operating system, and usage data.
              </li>
              <li>
                <strong>Communication Data:</strong> Information you provide
                through forms, emails, or during service interactions.
              </li>
            </ul>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>2.How We Use Your Information</h4>
            <p>We use the collected data to:</p>
            <ul>
              <li>Provide, operate, and maintain our services.</li>
              <li>
                Improve, personalize, and expand our website and offerings.
              </li>
              <li>
                Communicate with you, including for customer service and
                updates.
              </li>
              <li>Send you promotional materials (if you have opted in).</li>
              <li>Comply with legal obligations.</li>
            </ul>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>3. Sharing Your Information</h4>
            <p>
              We do not sell your personal information. However, we may share it
              with:
            </p>
            <ul>
              <li>
                Trusted third-party service providers assisting in our
                operations.
              </li>
              <li>
                Legal authorities if required by law or to protect our rights.
              </li>
              <li>
                Business partners, in case of mergers, acquisitions, or business
                restructuring.
              </li>
            </ul>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>4.Data Security</h4>
            <p>
              We take appropriate technical and organizational measures to
              protect your personal data against unauthorized access,
              alteration, disclosure, or destruction.
            </p>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>5. Your Rights</h4>
            <p>Depending on your location, you may have the right to:</p>
            <ul>
              <li>Access, correct, or delete your personal data.</li>
              <li>Object to or restrict certain processing.</li>
              <li>Withdraw consent (where applicable).</li>
            </ul>
            <p>
              To exercise any of these rights, please contact us at{" "}
              <Link href={"mailto:contact@dgtalists.com"}>
                contact@dgtalists.com
              </Link>
              .
            </p>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>6. Cookies and Tracking Technologies</h4>
            <p>
              We use cookies and similar tracking technologies to enhance user
              experience, analyze website traffic, and deliver targeted content.
              You can manage cookie preferences through your browser settings.
            </p>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>7. Third-Party Links</h4>
            <p>
              Our website may contain links to third-party websites. We are not
              responsible for their content or privacy practices. Please review
              their policies before providing any personal data.
            </p>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>8. Changes to This Policy</h4>
            <p>
              We reserve the right to modify this Privacy Policy at any time.
              Changes will be posted on this page with an updated effective
              date.
            </p>
          </div>
          <div className={styles.eachPrivacyWrap}>
            <h4>9. Contact Us</h4>
            <p>
              If you have any questions or concerns about this Privacy Policy,
              please contact us at: <Link href={"mailto:contact@dgtalists.com"}>
                contact@dgtalists.com
              </Link>
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
