import Head from "next/head";
import styles from "@/styles/About.module.css";
import Header from "@/component/Header/Header";
import Link from "next/link";
import ImageReveal from "@/component/ImageReveal/ImageReveal";
import AnimatedText from "@/component/AnimatedText/AnimatedText";
import { GoArrowUpRight, GoGlobe } from "react-icons/go";
import ContinuousScrollingSlider from "@/component/Continious/ContinuousScrolig";
import { PiSuitcaseSimpleLight } from "react-icons/pi";
import ParallaxBanner from "@/component/ParralaxBanner/ParallaxBanner";
import Counter from "@/component/Counter/Counter";
import { useEffect, useRef, useState } from "react";
import { BiSolidPhoneCall } from "react-icons/bi";
import Footer from "@/component/Footer/Footer";
import { FiChevronRight } from "react-icons/fi";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
import { RxEnvelopeClosed } from "react-icons/rx";
import { LuSearchCode } from "react-icons/lu";

export default function Team() {
  
  return (
    <>
      <Head>
        <title>Team</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ParallaxBanner backgroundImage="/images/team.jpg">
        <div className="container">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-9">
              <div className={styles.sectionLeft}>
                <h1>
                  <AnimatedText text={"Our Team"} highlightText={"Team"} />
                </h1>

                {/* Breadcrumb */}
                <div className={styles.breadcrumb}>
                  <ol className={styles.breadcrumbWrap}>
                    <li className={styles.breadcrumbList}>
                      <a href="/">Home</a>
                    </li>
                    <li className={`${styles.breadcrumbList} ${styles.active}`}>
                      <FiChevronRight />
                      Our Team
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ParallaxBanner>
      

      <section className={styles.teamMember}>
        <div className="container">
          <div className={styles.teamHeader}>
            <span className={styles.subtitle}>Meet our team</span>
            <h4 className={styles.title}>
              <AnimatedText
                text={"Meet Our Leadership Team"}
                highlightText={"Leadership"}
              />
            </h4>
          </div>
          <div className="row gx-5 justify-content-center">
            <div className="col-lg-3">
              <div className={styles.teamMemberBox}>
                <div className={styles.teamMemberImage}>
                  <ImageReveal
                    src={"/images/team1.jpg"}
                    alt={"team member"}
                    className={styles.teamImage}
                  />
                </div>
                <div className={styles.teamMemberContent}>
                  <h5>Sujay Saha</h5>
                  <p>CEO & Founder</p>
                </div>
              </div>
            </div>
            <div className="col-lg-3">
              <div className={styles.teamMemberBox}>
                <div className={styles.teamMemberImage}>
                  <ImageReveal
                    src={"/images/team2.jpg"}
                    alt={"team member"}
                    className={styles.teamImage}
                  />
                  {/* <div className={styles.teamSocial}>
                    <ul>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                      <li><Link href={"#"}><FaFacebookF /></Link></li>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                    </ul>
                  </div> */}
                </div>
                <div className={styles.teamMemberContent}>
                  <h5>Dipanjan Mondal</h5>
                  <p>Co-Founder & Director</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.teamMember}>
        <div className="container">
          <div className={styles.teamHeader}>
            <span className={styles.subtitle}>Meet our team</span>
            <h4 className={styles.title}>
              <AnimatedText
                text={"Meet Our Development Team"}
                highlightText={"Development"}
              />
            </h4>
          </div>
          <div className="row gx-5 justify-content-center">
            <div className="col-lg-3">
              <div className={styles.teamMemberBox}>
                <div className={styles.teamMemberImage}>
                  <ImageReveal
                    src={"/images/team1.jpg"}
                    alt={"team member"}
                    className={styles.teamImage}
                  />
                </div>
                <div className={styles.teamMemberContent}>
                  <h5>Sujay Saha</h5>
                  <p>CEO & Founder</p>
                </div>
              </div>
            </div>
            <div className="col-lg-3">
              <div className={styles.teamMemberBox}>
                <div className={styles.teamMemberImage}>
                  <ImageReveal
                    src={"/images/team2.jpg"}
                    alt={"team member"}
                    className={styles.teamImage}
                  />
                  {/* <div className={styles.teamSocial}>
                    <ul>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                      <li><Link href={"#"}><FaFacebookF /></Link></li>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                    </ul>
                  </div> */}
                </div>
                <div className={styles.teamMemberContent}>
                  <h5>Dipanjan Mondal</h5>
                  <p>Co-Founder & Director</p>
                </div>
              </div>
            </div>
            <div className="col-lg-3">
              <div className={styles.teamMemberBox}>
                <div className={styles.teamMemberImage}>
                  <ImageReveal
                    src={"/images/team1.jpg"}
                    alt={"team member"}
                    className={styles.teamImage}
                  />
                </div>
                <div className={styles.teamMemberContent}>
                  <h5>Sujay Saha</h5>
                  <p>CEO & Founder</p>
                </div>
              </div>
            </div>
            <div className="col-lg-3">
              <div className={styles.teamMemberBox}>
                <div className={styles.teamMemberImage}>
                  <ImageReveal
                    src={"/images/team2.jpg"}
                    alt={"team member"}
                    className={styles.teamImage}
                  />
                  {/* <div className={styles.teamSocial}>
                    <ul>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                      <li><Link href={"#"}><FaFacebookF /></Link></li>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                      <li><Link href={"#"}><FaLinkedinIn /></Link></li>
                    </ul>
                  </div> */}
                </div>
                <div className={styles.teamMemberContent}>
                  <h5>Dipanjan Mondal</h5>
                  <p>Co-Founder & Director</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.workTogether}>
        <div className="container">
          <div className={styles.togetherBox}>
            <div className={styles.headerSection}>
              <span className={styles.subtitle}>Let's Collaborate</span>
              <h4 className={styles.title}>
                <AnimatedText
                  text={"Let’s Build Your Next-Gen Enterprise Solution"}
                  highlightText={"Next-Gen Enterprise"}
                />
              </h4>
              <p>
                Looking to enhance your enterprise operations with a scalable,
                secure, and high-performance software solution? Let’s talk!
              </p>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <BiSolidPhoneCall />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Contact Us</h5>
                    <Link href={"tel:+91 89104 35874"}>+91 89104 35874</Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <GoGlobe />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>Our Website</h5>
                    <Link href={"https://dgtalists.com"}>
                      dgtalists.com
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-4">
                <div className={styles.eachContactItem}>
                  <div className={styles.contactIcon}>
                    <RxEnvelopeClosed />
                  </div>
                  <div className={styles.contactContent}>
                    <h5>e-mail address</h5>
                    <Link href={"mailto:contact@dgtalists.com"}>
                      contact@dgtalists.com{" "}
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
